#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py createsuperuser --noinput --username admin --email admin@example.com || echo "Superuser already exists"
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
