# Generated by Django 5.2.3 on 2025-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image_alt",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
