# Generated by Django 5.2.1 on 2025-06-10 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_eventtype_remove_servicecategory_prompt_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Projekt Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Ziele')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Anforderungen')),
                ('status', models.IntegerField(choices=[(0, 'Planung'), (1, 'Laufend'), (2, 'Pausiert'), (3, 'Abgeschlossen'), (4, 'Abgebrochen')], default=0, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ort')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max. Teilnehmer')),
                ('intern', models.BooleanField(default=False, verbose_name='Nur für Interne')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Kontakt Info')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='categories.itemtag')),
            ],
            options={
                'unique_together': {('project', 'tag')},
            },
        ),
    ]
