# Generated by Django 5.2.6 on 2025-09-20 12:41

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension(),
    ]
