# Generated by Django 5.2.6 on 2025-10-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Regal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Verlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Library abbreviation (only if ownership is library)', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='booked',
            field=models.BooleanField(default=False, help_text='Is the book currently booked?'),
        ),
        migrations.AddField(
            model_name='book',
            name='booked_till',
            field=models.DateField(blank=True, help_text='Booked until date (only if booked)', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ownership',
            field=models.CharField(choices=[('library', 'Library'), ('user', 'User')], default='user', help_text='Book ownership type', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='referenz',
            field=models.TextField(blank=True, help_text='References (multiple allowed)'),
        ),
        migrations.AddField(
            model_name='book',
            name='ort',
            field=models.ForeignKey(blank=True, help_text='Place of publication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.ort'),
        ),
        migrations.AddField(
            model_name='book',
            name='regal',
            field=models.ForeignKey(blank=True, help_text='Shelf location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.regal'),
        ),
        migrations.AddField(
            model_name='book',
            name='verlag',
            field=models.ForeignKey(blank=True, help_text='Publisher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.verlag'),
        ),
    ]
