# Generated by Django 5.2.7 on 2025-10-17 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbook",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="verlag",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Publisher",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="books.publisher",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="verlag",
            field=models.ForeignKey(
                blank=True,
                help_text="Publisher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="books.publisher",
            ),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="shelf",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Shelf location",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="books.shelf",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="shelf",
            field=models.ForeignKey(
                blank=True,
                help_text="Shelf location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="books.shelf",
            ),
        ),
    ]
