# Generated by Django 5.2.7 on 2025-10-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_language_historicalbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Raw metadata fetched from external sources like ISBN databases",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Raw metadata fetched from external sources like ISBN databases",
                null=True,
            ),
        ),
    ]
