FROM oven/bun:1-alpine

USER bun

WORKDIR /app

# Copy package files and bun.lockb
COPY --chown=bun:bun package.json bun.lockb ./

# Install dependencies with Bun
RUN bun install

# Copy source code
COPY --chown=bun:bun . .

EXPOSE 8080

CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
