# Generated by Django 5.2.1 on 2025-06-10 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_eventtype_remove_servicecategory_prompt_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Hour')),
                ('duration', models.DurationField(verbose_name='Typical Duration')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('availability', models.IntegerField(choices=[(0, 'Verfügbar'), (1, 'Überlastet'), (2, 'Nicht verfügbar'), (3, 'Urlaub')], default=0, verbose_name='Availability Status')),
                ('bookable', models.BooleanField(default=True, verbose_name='Bookable')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Profile Image')),
                ('profile_image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile Image Alt Text')),
                ('intern', models.BooleanField(default=False, verbose_name='Intern Only')),
                ('display_contact', models.BooleanField(default=True, verbose_name='Display Contact Info')),
                ('th_payment', models.BooleanField(blank=True, default=False, null=True, verbose_name='TH Payment Accepted')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='categories.servicecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.ImageField(upload_to='services/images/')),
                ('fname_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='services.service')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='categories.itemtag')),
            ],
            options={
                'unique_together': {('service', 'tag')},
            },
        ),
    ]
