volumes:
  bubble_local_postgres_data: {}
  bubble_local_redis_data: {}

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    image: bubble-frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src:z
    ports:
      - '127.0.0.1:8080:8080'

  backend: &backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: sh -c "uv sync && python3 manage.py migrate && uvicorn config.asgi:application --host 0.0.0.0 --reload"
    image: bubble-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./backend:/app:z
    env_file:
      - ./backend/.env-docker.local
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-not_set}
      - FRONTEND_URL=http://localhost:8080
    ports:
      - '127.0.0.1:8000:8000'

  postgres:
    image: docker.io/pgvector/pgvector:pg17
    restart: always
    volumes:
      - bubble_local_postgres_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - ./backend/.env-docker.local

  mailpit:
    image: docker.io/axllent/mailpit:latest
    ports:
      - '127.0.0.1:8025:8025'

  redis:
    image: ghcr.io/dragonflydb/dragonfly:latest
    restart: always
    ports:
      - '127.0.0.1:6377:6379'
    environment:
      # required to work with django-channels
      # https://github.com/dragonflydb/dragonfly/issues/182#issuecomment-1241624150
      DFLY_default_lua_flags: 'allow-undeclared-keys disable-atomicity'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    <<: *backend
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /app/.venv/bin/watchfiles --filter python /app/.venv/bin/celery.__main__.main --args '-A config.celery_app worker -l INFO'

  beat:
    <<: *backend
    image: bubble_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /app/.venv/bin/watchfiles --filter python /app/.venv/bin/celery.__main__.main --args '-A config.celery_app beat -l INFO'

  # flower:
  #   <<: *backend
  #   image: bubble_local_flower
  #   ports:
  #     - '5555:5555'
  #   command: /start-flower
