volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: bubble-frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - '8080:8888'

  backend: &backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: bubble-backend
    depends_on:
      - postgres
      - redis
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bubble_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *backend
    image: bubble_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *backend
    image: bubble_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *backend
    image: bubble_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: bubble_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
