volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: bubble-frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - '8080:8888'

  backend: &backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: bubble-backend
    depends_on:
      - postgres
      - redis
    command: /start
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    env_file:
      - ./backend/.env-docker.local

  postgres:
    image: docker.io/pgvector/pgvector:pg17
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./backend/.env-docker.local

  redis:
    image: ghcr.io/dragonflydb/dragonfly:latest

  celeryworker:
    <<: *backend
    command: /start-celeryworker

  celerybeat:
    <<: *backend
    command: /start-celerybeat

  # flower:
  #   <<: *backend
  #   command: /start-flower
