volumes:
  bubble_local_postgres_data: {}
  bubble_local_postgres_data_backups: {}
  bubble_local_redis_data: {}

services:
  frontend:
    image: bubble-frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - '3000:8888'

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bubble_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-not_set}
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bubble_production_postgres
    restart: always
    volumes:
      - bubble_local_postgres_data:/var/lib/postgresql/data
      - bubble_local_postgres_data_backups:/backups
    ports:
      - '8001:5432'
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    ports:
      - '8025:8025'

  redis:
    image: ghcr.io/dragonflydb/dragonfly:latest
    restart: always
    ports:
      - '127.0.0.1:6377:6379'
    environment:
      # required to work with django-channels
      # https://github.com/dragonflydb/dragonfly/issues/182#issuecomment-1241624150
      DFLY_default_lua_flags: 'allow-undeclared-keys disable-atomicity'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  # celeryworker:
  #   <<: *django
  #   image: bubble_local_celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailpit
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: bubble_local_celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailpit
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: bubble_local_flower
  #   ports:
  #     - '5555:5555'
  #   command: /start-flower
