# Generated by Django 5.2.1 on 2025-06-10 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_eventtype_remove_servicecategory_prompt_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('start_date', models.DateField(verbose_name='Start Datum')),
                ('end_date', models.DateField(verbose_name='End Datum')),
                ('is_full_day', models.BooleanField(default=False, verbose_name='Ganztägig')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Zeit')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Zeit')),
                ('location', models.CharField(max_length=255, verbose_name='Ort')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max. Teilnehmer')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Voraussetzungen')),
                ('materials_needed', models.TextField(blank=True, null=True, verbose_name='Benötigte Materialien')),
                ('intern', models.BooleanField(default=False, verbose_name='Nur für Interne')),
                ('registration_required', models.BooleanField(default=True, verbose_name='Anmeldung erforderlich')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Kontakt Info')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Profilbild')),
                ('profile_picture_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profilbild Alt Text')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.eventtype', verbose_name='Event Typ')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='Bild Datei')),
                ('fname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dateiname')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Bild',
                'verbose_name_plural': 'Event Bilder',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='events.event')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.itemtag')),
            ],
            options={
                'unique_together': {('event', 'tag')},
            },
        ),
    ]
