# Generated by Django 5.2.1 on 2025-06-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='prompt_description',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='prompt_name',
        ),
    ]
