# Generated by Django 5.2.11 on 2026-02-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="visibility",
            field=models.IntegerField(
                choices=[
                    (0, "Public"),
                    (1, "Authenticated"),
                    (2, "Specific"),
                    (3, "Private"),
                ],
                default=1,
                help_text="Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="visibility",
            field=models.IntegerField(
                choices=[
                    (0, "Public"),
                    (1, "Authenticated"),
                    (2, "Specific"),
                    (3, "Private"),
                ],
                default=1,
                help_text="Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).",
            ),
        ),
    ]
