# Generated by Django 5.2.7 on 2025-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Cancelled"),
                    (3, "Confirmed"),
                    (4, "Completed"),
                    (5, "Rejected"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Cancelled"),
                    (3, "Confirmed"),
                    (4, "Completed"),
                    (5, "Rejected"),
                ],
                default=1,
            ),
        ),
    ]
