# Generated by Django 5.2.7 on 2025-10-17 13:30

import django.utils.timezone
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="counter_offer",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Counter offer price for the booking",
                max_digits=10,
                null=True,
                verbose_name="Counter Offer",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="offer",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Offered price for the booking",
                max_digits=10,
                null=True,
                verbose_name="Offer",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Cancelled"),
                    (3, "Confirmed"),
                    (4, "Completed"),
                    (5, "Rejected"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time_from",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Time From",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time_to",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Time To"),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="counter_offer",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Counter offer price for the booking",
                max_digits=10,
                null=True,
                verbose_name="Counter Offer",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="offer",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Offered price for the booking",
                max_digits=10,
                null=True,
                verbose_name="Offer",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Cancelled"),
                    (3, "Confirmed"),
                    (4, "Completed"),
                    (5, "Rejected"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="time_from",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Time From",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="time_to",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Time To"),
        ),
    ]
