# Generated by Django 5.2.7 on 2025-10-19 10:00

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_counter_offer_alter_booking_offer_and_more"),
        ("items", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql="DROP EXTENSION IF EXISTS btree_gist;",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", 3), ("time_to__isnull", False)),
                expressions=[
                    (
                        models.Func(
                            models.F("time_from"),
                            models.F("time_to"),
                            function="tstzrange",
                        ),
                        "&&",
                    ),
                    (models.F("item"), "="),
                ],
                name="exclude_overlapping_confirmed_bookings_with_time_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", 3), ("time_to__isnull", True)),
                expressions=[(models.F("item"), "=")],
                name="exclude_overlapping_confirmed_bookings_without_time_to",
            ),
        ),
    ]
