# Generated by Django 5.2.7 on 2025-10-07 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_status_alter_historicalbooking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time_from",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="time_from",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
