// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

export type AuthToken = {
    username: string;
    password: string;
    readonly token: string;
};

/**
 * Serializer for Author model.
 */
export type Author = {
    readonly uuid: string;
    name: string;
    website?: string;
    bio?: string;
    readonly books_count: string;
};

export type BlankEnum = '';

/**
 * Serializer for Book detail view.
 */
export type Book = {
    readonly images: Array<Image>;
    readonly user: string;
    readonly first_image: string;
    sale_price?: string | null;
    rental_price?: string | null;
    readonly authors: Array<Author>;
    readonly genres: Array<Genre>;
    verlag: Publisher;
    shelf: Shelf;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    /**
     * Unique identifier for the item
     */
    readonly uuid: string;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    readonly sale_price_currency: string | null;
    readonly rental_price_currency: string | null;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
    isbn?: string;
    /**
     * Language of the book
     */
    language?: string;
    /**
     * Publication year
     */
    year?: number | null;
    /**
     * Main topic or subject
     */
    topic?: string;
};

/**
 * Serializer for Book list view.
 */
export type BookList = {
    readonly user: string;
    readonly first_image: string;
    sale_price?: string | null;
    rental_price?: string | null;
    readonly authors: Array<string>;
    readonly genres: Array<string>;
    readonly verlag_name: string;
    readonly shelf_name: string;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    /**
     * Unique identifier for the item
     */
    readonly uuid: string;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    readonly sale_price_currency: string | null;
    readonly rental_price_currency: string | null;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
    isbn?: string;
    /**
     * Language of the book
     */
    language?: string;
    /**
     * Publication year
     */
    year?: number | null;
    /**
     * Main topic or subject
     */
    topic?: string;
    /**
     * Publisher
     */
    verlag?: number | null;
    /**
     * Shelf location
     */
    shelf?: number | null;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type Booking = {
    readonly uuid: string;
    status?: StatusE2dEnum;
    /**
     * Unique identifier for the item
     */
    item: string;
    item_details: ItemMinimal;
    user: User;
    time_from?: string | null;
    time_to?: string | null;
    /**
     * Offered price for the booking
     */
    offer?: string | null;
    /**
     * Counter offer price for the booking
     */
    counter_offer?: string | null;
    accepted_by?: number | null;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Return unread_messages_count if it exists as an annotated field.
     */
    readonly unread_messages_count: number | null;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type BookingList = {
    readonly uuid: string;
    status?: StatusE2dEnum;
    /**
     * Unique identifier for the item
     */
    readonly item: string;
    item_details: ItemMinimal;
    user: User;
    readonly created_at: string;
    time_from?: string | null;
    time_to?: string | null;
    /**
     * Return unread_messages_count if it exists as an annotated field.
     */
    readonly unread_messages_count: number | null;
};

/**
 * * `books` - Books
 * * `clothing` - Clothing
 * * `electronics` - Electronics
 * * `furniture` - Furniture
 * * `garden` - Garden
 * * `kitchen` - Kitchen
 * * `other` - Other
 * * `rooms` - Rooms
 * * `sports` - Sports
 * * `tools` - Tools
 * * `toys` - Toys
 * * `vehicles` - Vehicles
 */
export type CategoryEnum = 'books' | 'clothing' | 'electronics' | 'furniture' | 'garden' | 'kitchen' | 'other' | 'rooms' | 'sports' | 'tools' | 'toys' | 'vehicles';

/**
 * * `0` - New
 * * `1` - Used
 * * `2` - Broken
 */
export type ConditionEnum = 0 | 1 | 2;

/**
 * Serializer for Genre model.
 */
export type Genre = {
    readonly uuid: string;
    name: string;
    description?: string;
    parent_genre?: number | null;
    readonly parent_genre_name: string | null;
    readonly parent_genre_uuid: string | null;
    readonly hierarchy: string;
    readonly books_count: string;
};

/**
 * Serializer for Image model.
 */
export type Image = {
    readonly uuid: string;
    original: string;
    ordering?: number | null;
    readonly thumbnail: string;
    readonly preview: string;
    /**
     * Unique identifier for the item
     */
    item: string;
};

/**
 * Serializer for Item model.
 */
export type Item = {
    readonly images: Array<Image>;
    readonly user: string;
    readonly first_image: string;
    sale_price?: string | null;
    rental_price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    /**
     * Unique identifier for the item
     */
    readonly uuid: string;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    readonly sale_price_currency: string | null;
    readonly rental_price_currency: string | null;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemList = {
    readonly user: string;
    readonly first_image: string;
    sale_price?: string | null;
    rental_price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    /**
     * Unique identifier for the item
     */
    readonly uuid: string;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    readonly sale_price_currency: string | null;
    readonly rental_price_currency: string | null;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemMinimal = {
    /**
     * Unique identifier for the item
     */
    readonly uuid: string;
    name?: string;
    readonly first_image: string;
};

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type Message = {
    readonly uuid: string;
    booking: string;
    readonly sender: string;
    readonly created_at: string;
    message: string;
    is_read?: boolean;
};

export type PaginatedAuthorList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Author>;
};

export type PaginatedBookListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BookList>;
};

export type PaginatedBookingListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BookingList>;
};

export type PaginatedGenreList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Genre>;
};

export type PaginatedImageList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Image>;
};

export type PaginatedItemListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ItemList>;
};

export type PaginatedMessageList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Message>;
};

export type PaginatedProfileList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Profile>;
};

export type PaginatedPublisherList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Publisher>;
};

export type PaginatedShelfList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Shelf>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

/**
 * Serializer for Author model.
 */
export type PatchedAuthor = {
    readonly uuid?: string;
    name?: string;
    website?: string;
    bio?: string;
    readonly books_count?: string;
};

/**
 * Serializer for Book detail view.
 */
export type PatchedBook = {
    readonly images?: Array<Image>;
    readonly user?: string;
    readonly first_image?: string;
    sale_price?: string | null;
    rental_price?: string | null;
    readonly authors?: Array<Author>;
    readonly genres?: Array<Genre>;
    verlag?: Publisher;
    shelf?: Shelf;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    /**
     * Unique identifier for the item
     */
    readonly uuid?: string;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    readonly sale_price_currency?: string | null;
    readonly rental_price_currency?: string | null;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
    isbn?: string;
    /**
     * Language of the book
     */
    language?: string;
    /**
     * Publication year
     */
    year?: number | null;
    /**
     * Main topic or subject
     */
    topic?: string;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type PatchedBooking = {
    readonly uuid?: string;
    status?: StatusE2dEnum;
    /**
     * Unique identifier for the item
     */
    item?: string;
    item_details?: ItemMinimal;
    user?: User;
    time_from?: string | null;
    time_to?: string | null;
    /**
     * Offered price for the booking
     */
    offer?: string | null;
    /**
     * Counter offer price for the booking
     */
    counter_offer?: string | null;
    accepted_by?: number | null;
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Return unread_messages_count if it exists as an annotated field.
     */
    readonly unread_messages_count?: number | null;
};

/**
 * Serializer for Genre model.
 */
export type PatchedGenre = {
    readonly uuid?: string;
    name?: string;
    description?: string;
    parent_genre?: number | null;
    readonly parent_genre_name?: string | null;
    readonly parent_genre_uuid?: string | null;
    readonly hierarchy?: string;
    readonly books_count?: string;
};

/**
 * Serializer for Image model.
 */
export type PatchedImage = {
    readonly uuid?: string;
    original?: string;
    ordering?: number | null;
    readonly thumbnail?: string;
    readonly preview?: string;
    /**
     * Unique identifier for the item
     */
    item?: string;
};

/**
 * Serializer for Item model.
 */
export type PatchedItem = {
    readonly images?: Array<Image>;
    readonly user?: string;
    readonly first_image?: string;
    sale_price?: string | null;
    rental_price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    /**
     * Unique identifier for the item
     */
    readonly uuid?: string;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    readonly sale_price_currency?: string | null;
    readonly rental_price_currency?: string | null;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
};

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type PatchedMessage = {
    readonly uuid?: string;
    booking?: string;
    readonly sender?: string;
    readonly created_at?: string;
    message?: string;
    is_read?: boolean;
};

export type PatchedProfile = {
    readonly username?: string;
    readonly name?: string;
    readonly email?: string;
    phone?: string;
    bio?: string;
    profile_image?: string | null;
};

/**
 * Serializer for Publisher model.
 */
export type PatchedPublisher = {
    readonly uuid?: string;
    name?: string;
    description?: string;
    readonly books_count?: string;
};

/**
 * Serializer for Shelf model.
 */
export type PatchedShelf = {
    readonly uuid?: string;
    name?: string;
    description?: string;
    readonly books_count?: string;
};

export type PatchedUser = {
    readonly uuid?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    /**
     * Name of User
     */
    name?: string;
    /**
     * Email address
     */
    email?: string;
};

export type Profile = {
    readonly username: string;
    readonly name: string;
    readonly email: string;
    phone?: string;
    bio?: string;
    profile_image?: string | null;
};

/**
 * Serializer for Publisher model.
 */
export type Publisher = {
    readonly uuid: string;
    name: string;
    description?: string;
    readonly books_count: string;
};

/**
 * * `h` - Hourly
 * * `d` - Daily
 * * `w` - Weekly
 */
export type RentalPeriodEnum = 'h' | 'd' | 'w';

/**
 * Serializer for Shelf model.
 */
export type Shelf = {
    readonly uuid: string;
    name: string;
    description?: string;
    readonly books_count: string;
};

/**
 * * `0` - Draft
 * * `1` - Processing
 * * `2` - Available
 * * `3` - Reserved
 * * `4` - Rented
 * * `5` - Sold
 */
export type Status402Enum = 0 | 1 | 2 | 3 | 4 | 5;

/**
 * * `1` - Pending
 * * `2` - Cancelled
 * * `3` - Confirmed
 * * `4` - Completed
 * * `5` - Rejected
 */
export type StatusE2dEnum = 1 | 2 | 3 | 4 | 5;

export type User = {
    readonly uuid: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Name of User
     */
    name?: string;
    /**
     * Email address
     */
    email?: string;
};

/**
 * Serializer for Author model.
 */
export type AuthorWritable = {
    name: string;
    website?: string;
    bio?: string;
};

/**
 * Serializer for Book detail view.
 */
export type BookWritable = {
    sale_price?: string | null;
    rental_price?: string | null;
    author_uuids?: Array<string>;
    genre_uuids?: Array<string>;
    verlag_uuid?: string | null;
    shelf_uuid?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
    isbn?: string;
    /**
     * Language of the book
     */
    language?: string;
    /**
     * Publication year
     */
    year?: number | null;
    /**
     * Main topic or subject
     */
    topic?: string;
};

/**
 * Serializer for Book list view.
 */
export type BookListWritable = {
    sale_price?: string | null;
    rental_price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
    isbn?: string;
    /**
     * Language of the book
     */
    language?: string;
    /**
     * Publication year
     */
    year?: number | null;
    /**
     * Main topic or subject
     */
    topic?: string;
    /**
     * Publisher
     */
    verlag?: number | null;
    /**
     * Shelf location
     */
    shelf?: number | null;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type BookingWritable = {
    status?: StatusE2dEnum;
    /**
     * Unique identifier for the item
     */
    item: string;
    time_from?: string | null;
    time_to?: string | null;
    /**
     * Offered price for the booking
     */
    offer?: string | null;
    /**
     * Counter offer price for the booking
     */
    counter_offer?: string | null;
    accepted_by?: number | null;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type BookingListWritable = {
    status?: StatusE2dEnum;
    time_from?: string | null;
    time_to?: string | null;
};

/**
 * Serializer for Genre model.
 */
export type GenreWritable = {
    name: string;
    description?: string;
    parent_genre?: number | null;
};

/**
 * Serializer for Image model.
 */
export type ImageWritable = {
    original: string;
    ordering?: number | null;
    /**
     * Unique identifier for the item
     */
    item: string;
};

/**
 * Serializer for Item model.
 */
export type ItemWritable = {
    sale_price?: string | null;
    rental_price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemListWritable = {
    sale_price?: string | null;
    rental_price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemMinimalWritable = {
    name?: string;
};

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type MessageWritable = {
    booking: string;
    message: string;
    is_read?: boolean;
};

/**
 * Serializer for Author model.
 */
export type PatchedAuthorWritable = {
    name?: string;
    website?: string;
    bio?: string;
};

/**
 * Serializer for Book detail view.
 */
export type PatchedBookWritable = {
    sale_price?: string | null;
    rental_price?: string | null;
    author_uuids?: Array<string>;
    genre_uuids?: Array<string>;
    verlag_uuid?: string | null;
    shelf_uuid?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
    isbn?: string;
    /**
     * Language of the book
     */
    language?: string;
    /**
     * Publication year
     */
    year?: number | null;
    /**
     * Main topic or subject
     */
    topic?: string;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type PatchedBookingWritable = {
    status?: StatusE2dEnum;
    /**
     * Unique identifier for the item
     */
    item?: string;
    time_from?: string | null;
    time_to?: string | null;
    /**
     * Offered price for the booking
     */
    offer?: string | null;
    /**
     * Counter offer price for the booking
     */
    counter_offer?: string | null;
    accepted_by?: number | null;
};

/**
 * Serializer for Genre model.
 */
export type PatchedGenreWritable = {
    name?: string;
    description?: string;
    parent_genre?: number | null;
};

/**
 * Serializer for Image model.
 */
export type PatchedImageWritable = {
    original?: string;
    ordering?: number | null;
    /**
     * Unique identifier for the item
     */
    item?: string;
};

/**
 * Serializer for Item model.
 */
export type PatchedItemWritable = {
    sale_price?: string | null;
    rental_price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Books
     * * `clothing` - Clothing
     * * `electronics` - Electronics
     * * `furniture` - Furniture
     * * `garden` - Garden
     * * `kitchen` - Kitchen
     * * `other` - Other
     * * `rooms` - Rooms
     * * `sports` - Sports
     * * `tools` - Tools
     * * `toys` - Toys
     * * `vehicles` - Vehicles
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Internal item, not for public display
     */
    internal?: boolean;
    /**
     * Display your contact information public
     */
    display_contact?: boolean;
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Allow self-service rental without owner approval
     */
    rental_self_service?: boolean;
    /**
     * Allow open-ended rentals without a return date
     */
    rental_open_end?: boolean;
    /**
     * Enable payment via internal payment system
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - New
     * * `1` - Used
     * * `2` - Broken
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status402Enum;
};

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type PatchedMessageWritable = {
    booking?: string;
    message?: string;
    is_read?: boolean;
};

export type PatchedProfileWritable = {
    phone?: string;
    bio?: string;
    profile_image?: string | null;
};

/**
 * Serializer for Publisher model.
 */
export type PatchedPublisherWritable = {
    name?: string;
    description?: string;
};

/**
 * Serializer for Shelf model.
 */
export type PatchedShelfWritable = {
    name?: string;
    description?: string;
};

export type PatchedUserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    /**
     * Name of User
     */
    name?: string;
    /**
     * Email address
     */
    email?: string;
};

export type ProfileWritable = {
    phone?: string;
    bio?: string;
    profile_image?: string | null;
};

/**
 * Serializer for Publisher model.
 */
export type PublisherWritable = {
    name: string;
    description?: string;
};

/**
 * Serializer for Shelf model.
 */
export type ShelfWritable = {
    name: string;
    description?: string;
};

export type UserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Name of User
     */
    name?: string;
    /**
     * Email address
     */
    email?: string;
};

export type AuthTokenCreateData = {
    body: AuthToken;
    path?: never;
    query?: never;
    url: '/api/auth-token/';
};

export type AuthTokenCreateResponses = {
    200: AuthToken;
};

export type AuthTokenCreateResponse = AuthTokenCreateResponses[keyof AuthTokenCreateResponses];

export type AuthorsListData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/authors/';
};

export type AuthorsListResponses = {
    200: PaginatedAuthorList;
};

export type AuthorsListResponse = AuthorsListResponses[keyof AuthorsListResponses];

export type AuthorsCreateData = {
    body: AuthorWritable;
    path?: never;
    query?: never;
    url: '/api/authors/';
};

export type AuthorsCreateResponses = {
    201: Author;
};

export type AuthorsCreateResponse = AuthorsCreateResponses[keyof AuthorsCreateResponses];

export type AuthorsDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/authors/{uuid}/';
};

export type AuthorsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AuthorsDestroyResponse = AuthorsDestroyResponses[keyof AuthorsDestroyResponses];

export type AuthorsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/authors/{uuid}/';
};

export type AuthorsRetrieveResponses = {
    200: Author;
};

export type AuthorsRetrieveResponse = AuthorsRetrieveResponses[keyof AuthorsRetrieveResponses];

export type AuthorsPartialUpdateData = {
    body?: PatchedAuthorWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/authors/{uuid}/';
};

export type AuthorsPartialUpdateResponses = {
    200: Author;
};

export type AuthorsPartialUpdateResponse = AuthorsPartialUpdateResponses[keyof AuthorsPartialUpdateResponses];

export type AuthorsUpdateData = {
    body: AuthorWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/authors/{uuid}/';
};

export type AuthorsUpdateResponses = {
    200: Author;
};

export type AuthorsUpdateResponse = AuthorsUpdateResponses[keyof AuthorsUpdateResponses];

export type BookingsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/bookings/';
};

export type BookingsListResponses = {
    200: PaginatedBookingListList;
};

export type BookingsListResponse = BookingsListResponses[keyof BookingsListResponses];

export type BookingsCreateData = {
    body: BookingWritable;
    path?: never;
    query?: never;
    url: '/api/bookings/';
};

export type BookingsCreateResponses = {
    201: Booking;
};

export type BookingsCreateResponse = BookingsCreateResponses[keyof BookingsCreateResponses];

export type BookingsDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/bookings/{uuid}/';
};

export type BookingsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type BookingsDestroyResponse = BookingsDestroyResponses[keyof BookingsDestroyResponses];

export type BookingsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/bookings/{uuid}/';
};

export type BookingsRetrieveResponses = {
    200: Booking;
};

export type BookingsRetrieveResponse = BookingsRetrieveResponses[keyof BookingsRetrieveResponses];

export type BookingsPartialUpdateData = {
    body?: PatchedBookingWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/bookings/{uuid}/';
};

export type BookingsPartialUpdateResponses = {
    200: Booking;
};

export type BookingsPartialUpdateResponse = BookingsPartialUpdateResponses[keyof BookingsPartialUpdateResponses];

export type BookingsUpdateData = {
    body: BookingWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/bookings/{uuid}/';
};

export type BookingsUpdateResponses = {
    200: Booking;
};

export type BookingsUpdateResponse = BookingsUpdateResponses[keyof BookingsUpdateResponses];

export type BooksListData = {
    body?: never;
    path?: never;
    query?: {
        author?: number;
        author_name?: string;
        genre?: number;
        genre_name?: string;
        isbn?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        publisher?: number;
        publisher_name?: string;
        /**
         * A search term.
         */
        search?: string;
        shelf?: number;
        shelf_name?: string;
        topic?: string;
        year?: number;
        year_max?: number;
        year_min?: number;
    };
    url: '/api/books/';
};

export type BooksListResponses = {
    200: PaginatedBookListList;
};

export type BooksListResponse = BooksListResponses[keyof BooksListResponses];

export type BooksCreateData = {
    body?: BookWritable;
    path?: never;
    query?: never;
    url: '/api/books/';
};

export type BooksCreateResponses = {
    201: Book;
};

export type BooksCreateResponse = BooksCreateResponses[keyof BooksCreateResponses];

export type BooksDestroyData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/books/{uuid}/';
};

export type BooksDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type BooksDestroyResponse = BooksDestroyResponses[keyof BooksDestroyResponses];

export type BooksRetrieveData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/books/{uuid}/';
};

export type BooksRetrieveResponses = {
    200: Book;
};

export type BooksRetrieveResponse = BooksRetrieveResponses[keyof BooksRetrieveResponses];

export type BooksPartialUpdateData = {
    body?: PatchedBookWritable;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/books/{uuid}/';
};

export type BooksPartialUpdateResponses = {
    200: Book;
};

export type BooksPartialUpdateResponse = BooksPartialUpdateResponses[keyof BooksPartialUpdateResponses];

export type BooksUpdateData = {
    body?: BookWritable;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/books/{uuid}/';
};

export type BooksUpdateResponses = {
    200: Book;
};

export type BooksUpdateResponse = BooksUpdateResponses[keyof BooksUpdateResponses];

export type BooksIsbnUpdateUpdateData = {
    body?: {
        /**
         * ISBN number to fetch book details from OpenLibrary API. If not provided, uses the book's existing ISBN.
         */
        isbn?: string;
    };
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/books/{uuid}/isbn_update/';
};

export type BooksIsbnUpdateUpdateResponses = {
    200: Book;
};

export type BooksIsbnUpdateUpdateResponse = BooksIsbnUpdateUpdateResponses[keyof BooksIsbnUpdateUpdateResponses];

export type GenresListData = {
    body?: never;
    path?: never;
    query?: {
        has_parent?: boolean;
        name?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent_genre?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/genres/';
};

export type GenresListResponses = {
    200: PaginatedGenreList;
};

export type GenresListResponse = GenresListResponses[keyof GenresListResponses];

export type GenresCreateData = {
    body: GenreWritable;
    path?: never;
    query?: never;
    url: '/api/genres/';
};

export type GenresCreateResponses = {
    201: Genre;
};

export type GenresCreateResponse = GenresCreateResponses[keyof GenresCreateResponses];

export type GenresDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/genres/{uuid}/';
};

export type GenresDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type GenresDestroyResponse = GenresDestroyResponses[keyof GenresDestroyResponses];

export type GenresRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/genres/{uuid}/';
};

export type GenresRetrieveResponses = {
    200: Genre;
};

export type GenresRetrieveResponse = GenresRetrieveResponses[keyof GenresRetrieveResponses];

export type GenresPartialUpdateData = {
    body?: PatchedGenreWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/genres/{uuid}/';
};

export type GenresPartialUpdateResponses = {
    200: Genre;
};

export type GenresPartialUpdateResponse = GenresPartialUpdateResponses[keyof GenresPartialUpdateResponses];

export type GenresUpdateData = {
    body: GenreWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/genres/{uuid}/';
};

export type GenresUpdateResponses = {
    200: Genre;
};

export type GenresUpdateResponse = GenresUpdateResponses[keyof GenresUpdateResponses];

export type ImagesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/images/';
};

export type ImagesListResponses = {
    200: PaginatedImageList;
};

export type ImagesListResponse = ImagesListResponses[keyof ImagesListResponses];

export type ImagesCreateData = {
    body: ImageWritable;
    path?: never;
    query?: never;
    url: '/api/images/';
};

export type ImagesCreateResponses = {
    201: Image;
};

export type ImagesCreateResponse = ImagesCreateResponses[keyof ImagesCreateResponses];

export type ImagesDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/images/{uuid}/';
};

export type ImagesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ImagesDestroyResponse = ImagesDestroyResponses[keyof ImagesDestroyResponses];

export type ImagesRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/images/{uuid}/';
};

export type ImagesRetrieveResponses = {
    200: Image;
};

export type ImagesRetrieveResponse = ImagesRetrieveResponses[keyof ImagesRetrieveResponses];

export type ImagesPartialUpdateData = {
    body?: PatchedImageWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/images/{uuid}/';
};

export type ImagesPartialUpdateResponses = {
    200: Image;
};

export type ImagesPartialUpdateResponse = ImagesPartialUpdateResponses[keyof ImagesPartialUpdateResponses];

export type ImagesUpdateData = {
    body: ImageWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/images/{uuid}/';
};

export type ImagesUpdateResponses = {
    200: Image;
};

export type ImagesUpdateResponse = ImagesUpdateResponses[keyof ImagesUpdateResponses];

export type ItemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category of the item
         *
         * * `books` - Books
         * * `clothing` - Clothing
         * * `electronics` - Electronics
         * * `furniture` - Furniture
         * * `garden` - Garden
         * * `kitchen` - Kitchen
         * * `other` - Other
         * * `rooms` - Rooms
         * * `sports` - Sports
         * * `tools` - Tools
         * * `toys` - Toys
         * * `vehicles` - Vehicles
         */
        category?: 'books' | 'clothing' | 'electronics' | 'furniture' | 'garden' | 'kitchen' | 'other' | 'rooms' | 'sports' | 'tools' | 'toys' | 'vehicles';
        created_after?: string;
        created_before?: string;
        max_rental_price?: number;
        max_sale_price?: number;
        min_rental_price?: number;
        min_sale_price?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        published?: boolean;
        /**
         * A search term.
         */
        search?: string;
        /**
         * * `0` - Draft
         * * `1` - Processing
         * * `2` - Available
         * * `3` - Reserved
         * * `4` - Rented
         * * `5` - Sold
         */
        status?: Array<0 | 1 | 2 | 3 | 4 | 5>;
        user?: number;
    };
    url: '/api/items/';
};

export type ItemsListResponses = {
    200: PaginatedItemListList;
};

export type ItemsListResponse = ItemsListResponses[keyof ItemsListResponses];

export type ItemsCreateData = {
    body?: ItemWritable;
    path?: never;
    query?: never;
    url: '/api/items/';
};

export type ItemsCreateResponses = {
    201: Item;
};

export type ItemsCreateResponse = ItemsCreateResponses[keyof ItemsCreateResponses];

export type ItemsDestroyData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/items/{uuid}/';
};

export type ItemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ItemsDestroyResponse = ItemsDestroyResponses[keyof ItemsDestroyResponses];

export type ItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/items/{uuid}/';
};

export type ItemsRetrieveResponses = {
    200: Item;
};

export type ItemsRetrieveResponse = ItemsRetrieveResponses[keyof ItemsRetrieveResponses];

export type ItemsPartialUpdateData = {
    body?: PatchedItemWritable;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/items/{uuid}/';
};

export type ItemsPartialUpdateResponses = {
    200: Item;
};

export type ItemsPartialUpdateResponse = ItemsPartialUpdateResponses[keyof ItemsPartialUpdateResponses];

export type ItemsUpdateData = {
    body?: ItemWritable;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/items/{uuid}/';
};

export type ItemsUpdateResponses = {
    200: Item;
};

export type ItemsUpdateResponse = ItemsUpdateResponses[keyof ItemsUpdateResponses];

export type ItemsAiDescribeUpdateData = {
    body?: ItemWritable;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/items/{uuid}/ai_describe/';
};

export type ItemsAiDescribeUpdateResponses = {
    200: Item;
};

export type ItemsAiDescribeUpdateResponse = ItemsAiDescribeUpdateResponses[keyof ItemsAiDescribeUpdateResponses];

export type ItemsAiImageUpdateData = {
    body?: ItemWritable;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/items/{uuid}/ai_image/';
};

export type ItemsAiImageUpdateResponses = {
    200: Item;
};

export type ItemsAiImageUpdateResponse = ItemsAiImageUpdateResponses[keyof ItemsAiImageUpdateResponses];

export type ItemsReorderImagesUpdateData = {
    body?: ItemWritable;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/items/{uuid}/reorder_images/';
};

export type ItemsReorderImagesUpdateResponses = {
    200: Item;
};

export type ItemsReorderImagesUpdateResponse = ItemsReorderImagesUpdateResponses[keyof ItemsReorderImagesUpdateResponses];

export type MessagesListData = {
    body?: never;
    path?: never;
    query?: {
        booking?: string;
        created_at_after?: string;
        created_at_before?: string;
        is_read?: boolean;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        sender?: number;
        /**
         * Unread messages received by current user
         */
        unread_received?: boolean;
    };
    url: '/api/messages/';
};

export type MessagesListResponses = {
    200: PaginatedMessageList;
};

export type MessagesListResponse = MessagesListResponses[keyof MessagesListResponses];

export type MessagesCreateData = {
    body: MessageWritable;
    path?: never;
    query?: never;
    url: '/api/messages/';
};

export type MessagesCreateResponses = {
    201: Message;
};

export type MessagesCreateResponse = MessagesCreateResponses[keyof MessagesCreateResponses];

export type MessagesDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/messages/{uuid}/';
};

export type MessagesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type MessagesDestroyResponse = MessagesDestroyResponses[keyof MessagesDestroyResponses];

export type MessagesRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/messages/{uuid}/';
};

export type MessagesRetrieveResponses = {
    200: Message;
};

export type MessagesRetrieveResponse = MessagesRetrieveResponses[keyof MessagesRetrieveResponses];

export type MessagesPartialUpdateData = {
    body?: PatchedMessageWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/messages/{uuid}/';
};

export type MessagesPartialUpdateResponses = {
    200: Message;
};

export type MessagesPartialUpdateResponse = MessagesPartialUpdateResponses[keyof MessagesPartialUpdateResponses];

export type MessagesUpdateData = {
    body: MessageWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/messages/{uuid}/';
};

export type MessagesUpdateResponses = {
    200: Message;
};

export type MessagesUpdateResponse = MessagesUpdateResponses[keyof MessagesUpdateResponses];

export type ProfilesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/profiles/';
};

export type ProfilesListResponses = {
    200: PaginatedProfileList;
};

export type ProfilesListResponse = ProfilesListResponses[keyof ProfilesListResponses];

export type ProfilesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/profiles/{id}/';
};

export type ProfilesRetrieveResponses = {
    200: Profile;
};

export type ProfilesRetrieveResponse = ProfilesRetrieveResponses[keyof ProfilesRetrieveResponses];

export type ProfilesMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profiles/me/';
};

export type ProfilesMeRetrieveResponses = {
    200: Profile;
};

export type ProfilesMeRetrieveResponse = ProfilesMeRetrieveResponses[keyof ProfilesMeRetrieveResponses];

export type ProfilesMePartialUpdateData = {
    body?: PatchedProfileWritable;
    path?: never;
    query?: never;
    url: '/api/profiles/me/';
};

export type ProfilesMePartialUpdateResponses = {
    200: Profile;
};

export type ProfilesMePartialUpdateResponse = ProfilesMePartialUpdateResponses[keyof ProfilesMePartialUpdateResponses];

export type PublicBookingsListData = {
    body?: never;
    path?: never;
    query?: {
        created_at_after?: string;
        created_at_before?: string;
        item?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * * `1` - Pending
         * * `2` - Cancelled
         * * `3` - Confirmed
         * * `4` - Completed
         * * `5` - Rejected
         */
        status?: Array<1 | 2 | 3 | 4 | 5>;
        user?: number;
    };
    url: '/api/public-bookings/';
};

export type PublicBookingsListResponses = {
    200: PaginatedBookingListList;
};

export type PublicBookingsListResponse = PublicBookingsListResponses[keyof PublicBookingsListResponses];

export type PublicBookingsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/public-bookings/{uuid}/';
};

export type PublicBookingsRetrieveResponses = {
    200: Booking;
};

export type PublicBookingsRetrieveResponse = PublicBookingsRetrieveResponses[keyof PublicBookingsRetrieveResponses];

export type PublicItemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category of the item
         *
         * * `books` - Books
         * * `clothing` - Clothing
         * * `electronics` - Electronics
         * * `furniture` - Furniture
         * * `garden` - Garden
         * * `kitchen` - Kitchen
         * * `other` - Other
         * * `rooms` - Rooms
         * * `sports` - Sports
         * * `tools` - Tools
         * * `toys` - Toys
         * * `vehicles` - Vehicles
         */
        category?: 'books' | 'clothing' | 'electronics' | 'furniture' | 'garden' | 'kitchen' | 'other' | 'rooms' | 'sports' | 'tools' | 'toys' | 'vehicles';
        created_after?: string;
        created_before?: string;
        max_rental_price?: number;
        max_sale_price?: number;
        min_rental_price?: number;
        min_sale_price?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        published?: boolean;
        /**
         * A search term.
         */
        search?: string;
        /**
         * * `0` - Draft
         * * `1` - Processing
         * * `2` - Available
         * * `3` - Reserved
         * * `4` - Rented
         * * `5` - Sold
         */
        status?: Array<0 | 1 | 2 | 3 | 4 | 5>;
        user?: number;
    };
    url: '/api/public-items/';
};

export type PublicItemsListResponses = {
    200: PaginatedItemListList;
};

export type PublicItemsListResponse = PublicItemsListResponses[keyof PublicItemsListResponses];

export type PublicItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the item
         */
        uuid: string;
    };
    query?: never;
    url: '/api/public-items/{uuid}/';
};

export type PublicItemsRetrieveResponses = {
    200: Item;
};

export type PublicItemsRetrieveResponse = PublicItemsRetrieveResponses[keyof PublicItemsRetrieveResponses];

export type PublishersListData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/publishers/';
};

export type PublishersListResponses = {
    200: PaginatedPublisherList;
};

export type PublishersListResponse = PublishersListResponses[keyof PublishersListResponses];

export type PublishersCreateData = {
    body: PublisherWritable;
    path?: never;
    query?: never;
    url: '/api/publishers/';
};

export type PublishersCreateResponses = {
    201: Publisher;
};

export type PublishersCreateResponse = PublishersCreateResponses[keyof PublishersCreateResponses];

export type PublishersDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/publishers/{uuid}/';
};

export type PublishersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type PublishersDestroyResponse = PublishersDestroyResponses[keyof PublishersDestroyResponses];

export type PublishersRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/publishers/{uuid}/';
};

export type PublishersRetrieveResponses = {
    200: Publisher;
};

export type PublishersRetrieveResponse = PublishersRetrieveResponses[keyof PublishersRetrieveResponses];

export type PublishersPartialUpdateData = {
    body?: PatchedPublisherWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/publishers/{uuid}/';
};

export type PublishersPartialUpdateResponses = {
    200: Publisher;
};

export type PublishersPartialUpdateResponse = PublishersPartialUpdateResponses[keyof PublishersPartialUpdateResponses];

export type PublishersUpdateData = {
    body: PublisherWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/publishers/{uuid}/';
};

export type PublishersUpdateResponses = {
    200: Publisher;
};

export type PublishersUpdateResponse = PublishersUpdateResponses[keyof PublishersUpdateResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'de' | 'en';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type ShelvesListData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/shelves/';
};

export type ShelvesListResponses = {
    200: PaginatedShelfList;
};

export type ShelvesListResponse = ShelvesListResponses[keyof ShelvesListResponses];

export type ShelvesCreateData = {
    body: ShelfWritable;
    path?: never;
    query?: never;
    url: '/api/shelves/';
};

export type ShelvesCreateResponses = {
    201: Shelf;
};

export type ShelvesCreateResponse = ShelvesCreateResponses[keyof ShelvesCreateResponses];

export type ShelvesDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/shelves/{uuid}/';
};

export type ShelvesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ShelvesDestroyResponse = ShelvesDestroyResponses[keyof ShelvesDestroyResponses];

export type ShelvesRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/shelves/{uuid}/';
};

export type ShelvesRetrieveResponses = {
    200: Shelf;
};

export type ShelvesRetrieveResponse = ShelvesRetrieveResponses[keyof ShelvesRetrieveResponses];

export type ShelvesPartialUpdateData = {
    body?: PatchedShelfWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/shelves/{uuid}/';
};

export type ShelvesPartialUpdateResponses = {
    200: Shelf;
};

export type ShelvesPartialUpdateResponse = ShelvesPartialUpdateResponses[keyof ShelvesPartialUpdateResponses];

export type ShelvesUpdateData = {
    body: ShelfWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/shelves/{uuid}/';
};

export type ShelvesUpdateResponses = {
    200: Shelf;
};

export type ShelvesUpdateResponse = ShelvesUpdateResponses[keyof ShelvesUpdateResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/users/';
};

export type UsersListResponses = {
    200: PaginatedUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/users/{uuid}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/users/{uuid}/';
};

export type UsersPartialUpdateResponses = {
    200: User;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/users/{uuid}/';
};

export type UsersUpdateResponses = {
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: User;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];
