# Generated by Django 5.2.1 on 2025-06-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fname_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='profile_img_frame_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='fname',
            field=models.ImageField(upload_to='items/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(0, 'Verkaufen'), (1, 'Weggeben'), (2, 'Ausleihen'), (3, 'Brauchen')], default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='profile_img_frame',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Neu'), (1, 'Gebraucht'), (2, 'Alt')], null=True),
        ),
    ]
