# Generated by Django 5.2.7 on 2025-10-12 20:03

import uuid
from django.db import migrations, models


def fill_uuid_field(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.filter(uuid__isnull=True):
        user.uuid = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0003_rename_intern_profile_internal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_login",
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=fill_uuid_field,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
