#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Change to app directory
cd /app

# Run Django commands using the virtual environment directly
python3 manage.py migrate
python3 manage.py createsuperuser --noinput --username admin --email admin@example.com || echo "Superuser already exists"
exec uvicorn config.asgi:application --host 0.0.0.0 --reload
