# Generated by Django 5.2.3 on 2025-07-16 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='List Name')),
                ('is_default', models.BooleanField(default=False, help_text='Default list for new favorites', verbose_name='Default List')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('editors', models.ManyToManyField(blank=True, help_text='Users who can edit and delete items in this list', related_name='editable_favorite_lists', to=settings.AUTH_USER_MODEL, verbose_name='Editors')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users who can view this list but cannot edit it', related_name='shared_favorite_lists', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_favorite_lists', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Favorite List',
                'verbose_name_plural': 'Favorite Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_list',
            field=models.ForeignKey(blank=True, help_text='The list this favorite belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='favorites.favoritelist', verbose_name='Favorite List'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'url', 'favorite_list')},
        ),
    ]
