#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'

# Set AUTO_COLLECTSTATIC=1 to collect static assets
if [ "${AUTO_COLLECTSTATIC:-}" = "1" ]; then
    # >&2 echo 'Collecting static files (python manage.py collectstatic)'
    # Use manage.py from project root; fail the container if collectstatic fails
    python manage.py collectstatic --noinput
fi

exec "$@"
