#!/bin/bash

set -o errexit
set -o nounset

# Change to app directory
cd /app

exec /app/.venv/bin/watchfiles --filter python /app/.venv/bin/celery.__main__.main --args '-A config.celery_app worker -l INFO'
