# Generated by Django 5.2.3 on 2025-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcategory",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemcategory",
            name="prompt_description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemcategory",
            name="prompt_name",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
