# Generated by Django 5.2.3 on 2025-06-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_eventtype_remove_servicecategory_prompt_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
