# Generated by Django 5.2.3 on 2025-06-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_eventtype_remove_servicecategory_prompt_description_and_more'),
        ('items', '0003_alter_item_item_type_alter_item_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='ItemTag',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
