# Generated by Django 5.2.3 on 2025-07-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_itemcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='content_type',
            field=models.CharField(blank=True, help_text="Type identifier (e.g., 'thing', 'event', 'service')", max_length=50),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='optional_fields',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema for optional fields specific to this category'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='required_fields',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema for required fields specific to this category'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='url_slug',
            field=models.SlugField(blank=True, help_text="URL path for this content type (e.g., 'sachen', 'events')"),
        ),
    ]
