# Generated by Django 5.2.3 on 2025-06-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_delete_eventtype'),
        ('items', '0003_alter_item_item_type_alter_item_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTag',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
