# Generated by Django 5.2.3 on 2025-07-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_setup_initial_content_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='content_type',
        ),
    ]
