# Generated by Django 5.2.3 on 2025-07-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_fix_status_field_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='filter_fields',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema for fields that should appear in list filters'),
        ),
    ]
