# Generated by Django 5.2.3 on 2025-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_setup_filter_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='filter_fields',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='optional_fields',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='required_fields',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text="JSON schema for custom fields specific to this category. Format: {'field_name': {'type': 'choice', 'label': 'Size', 'choices': ['S', 'M', 'L'], 'required': true}}"),
        ),
    ]
