# Generated by Django 5.2.3 on 2025-07-02 08:18

from django.db import migrations


def migrate_custom_fields_data(apps, schema_editor):
    """
    This migration should have converted old required_fields and optional_fields
    to the new custom_fields format with required attribute, but since those 
    fields were already removed in the previous migration, we'll set up 
    some example data for testing.
    """
    ItemCategory = apps.get_model('categories', 'ItemCategory')
    
    # Set up example custom fields for root categories
    for category in ItemCategory.objects.filter(parent_category__isnull=True):
        if category.url_slug == 'sachen':  # Example for "Sachen" category
            category.custom_fields = {
                'size': {
                    'type': 'choice',
                    'label': 'Größe',
                    'choices': ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
                    'required': True
                },
                'condition': {
                    'type': 'choice', 
                    'label': 'Zustand',
                    'choices': [
                        {'key': 'new', 'value': 'Neu'},
                        {'key': 'used', 'value': 'Gebraucht'}, 
                        {'key': 'old', 'value': 'Alt'}
                    ],
                    'required': True
                },
                'brand': {
                    'type': 'text',
                    'label': 'Marke',
                    'required': False
                }
            }
            category.save()


def reverse_migrate_custom_fields_data(apps, schema_editor):
    """Reverse migration - clear custom_fields"""
    ItemCategory = apps.get_model('categories', 'ItemCategory')
    ItemCategory.objects.update(custom_fields={})


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_simplify_custom_fields'),
    ]

    operations = [
        migrations.RunPython(
            migrate_custom_fields_data,
            reverse_migrate_custom_fields_data
        ),
    ]
