# Generated by Django 5.2.3 on 2025-07-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_migrate_custom_fields_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
