# Generated by Django 5.2.3 on 2025-07-04 21:09

from django.db import migrations


def add_default_emojis(apps, schema_editor):
    ItemCategory = apps.get_model('categories', 'ItemCategory')
    
    # Update existing categories with default emojis
    category_emojis = {
        'zeug': '📦',
        'raeme': '🛋️',
    }
    
    for url_slug, emoji in category_emojis.items():
        ItemCategory.objects.filter(url_slug=url_slug).update(emoji=emoji)


def remove_emojis(apps, schema_editor):
    ItemCategory = apps.get_model('categories', 'ItemCategory')
    ItemCategory.objects.update(emoji='')


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_itemcategory_emoji'),
    ]

    operations = [
        migrations.RunPython(add_default_emojis, remove_emojis),
    ]
