# Generated by Django 5.2.3 on 2025-07-05 07:27

from django.db import migrations


def set_category_ordering(apps, schema_editor):
    ItemCategory = apps.get_model('categories', 'ItemCategory')
    
    # Define ordering for root categories
    ordering_map = {
        'zeug': 1,  # Things first
        'raeme': 2,  # Rooms second
        'aktivitaeten': 3,  # Activities third
    }
    
    # Update ordering for root categories
    for category in ItemCategory.objects.filter(parent_category__isnull=True):
        if category.url_slug in ordering_map:
            category.ordering = ordering_map[category.url_slug]
            category.save()


def reverse_category_ordering(apps, schema_editor):
    ItemCategory = apps.get_model('categories', 'ItemCategory')
    # Reset all to default
    ItemCategory.objects.all().update(ordering=1)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_add_ordering'),
    ]

    operations = [
        migrations.RunPython(set_category_ordering, reverse_category_ordering),
    ]
