# Generated by Django 5.2.3 on 2025-07-07 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_set_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of field names to display as filters. Can include both Item model fields and custom fields.', size=None),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='lower_tag',
            field=models.CharField(blank=True, help_text='Custom field name to display in lower tag on item cards', max_length=50),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='sort_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of field names available for sorting. Custom fields will allow both ascending and descending sort.', size=None),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='upper_tag',
            field=models.CharField(blank=True, help_text='Custom field name to display in upper tag on item cards', max_length=50),
        ),
    ]
