# Generated by Django 5.2.3 on 2025-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0014_set_default_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
