# Generated by Django 5.2.3 on 2025-07-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_alter_itemcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='url_slug',
        ),
    ]
