# Generated by Django 5.2.3 on 2025-07-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_remove_itemcategory_custom_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='prompt_description',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='prompt_name',
        ),
    ]
