#!/bin/bash

set -o errexit
set -o nounset

# Change to app directory
cd /app

until timeout 10 /app/.venv/bin/celery -A config.celery_app inspect ping; do
    >&2 echo "Celery workers not available"
done

echo 'Starting flower'

exec /app/.venv/bin/watchfiles --filter python /app/.venv/bin/celery.__main__.main \
    --args \
    "-A config.celery_app -b \"${REDIS_URL}\" flower --basic_auth=\"${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}\""
