# Generated by Django 5.2.3 on 2025-07-10 07:58

import bubble.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the room', max_length=255, verbose_name='Name')),
                ('description', models.TextField(help_text='Detailed description of the room', verbose_name='Description')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the room', null=True, upload_to=bubble.rooms.models.upload_to_room_photos, verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
    ]
