# Generated by Django 5.2.3 on 2025-06-21 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.ImageField(upload_to="items/images/")),
                ("fname_alt", models.CharField(blank=True, max_length=255, null=True)),
                ("ordering", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("intern", models.BooleanField(default=False)),
                ("display_contact", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "th_payment",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "New"), (1, "Used"), (2, "Old")],
                        null=True,
                    ),
                ),
                (
                    "item_type",
                    models.IntegerField(
                        choices=[
                            (0, "For Sale"),
                            (1, "Give Away"),
                            (2, "Borrow"),
                            (3, "Need"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "profile_img_frame",
                    models.ImageField(blank=True, null=True, upload_to="items/"),
                ),
                (
                    "profile_img_frame_alt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="categories.itemcategory",
                    ),
                ),
            ],
        ),
    ]
