# Generated by Django 5.2.3

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bubble.items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                (
                    "ordering",
                    models.IntegerField(
                        default=1,
                        help_text="Order of display in navigation menu (lower numbers appear first)",
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="items.itemcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Item Categories",
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the item",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "internal",
                    models.BooleanField(
                        default=False, help_text="Internal item, not for public display"
                    ),
                ),
                (
                    "display_contact",
                    models.BooleanField(
                        default=False, help_text="Display your contact information public"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable payment via internal payment system"
                    ),
                ),
                (
                    "item_type",
                    models.IntegerField(
                        choices=[(0, "For Sale"), (1, "Rent")], default=0
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "New"), (1, "Used"), (2, "Broken")],
                        default=1,
                        help_text="Condition of the item",
                    ),
                ),
                (
                    "processing_status",
                    models.IntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Processing"),
                            (2, "Completed"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(
                        blank=True,
                        help_text="Temporal workflow ID for AI processing",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="items.itemcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original",
                    models.ImageField(
                        max_length=255, upload_to=bubble.items.models.upload_to_item_images
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "ordering"],
            },
        ),
    ]