# Generated by Django 5.2.7 on 2025-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="rental_open_end",
            field=models.BooleanField(
                default=False,
                help_text="Allow open-ended rentals without a return date",
            ),
        ),
        migrations.AddField(
            model_name="historicalitem",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[("h", "Hourly"), ("d", "Daily"), ("w", "Weekly")],
                default="h",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="historicalitem",
            name="rental_self_service",
            field=models.BooleanField(
                default=False,
                help_text="Allow self-service rental without owner approval",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rental_open_end",
            field=models.BooleanField(
                default=False,
                help_text="Allow open-ended rentals without a return date",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[("h", "Hourly"), ("d", "Daily"), ("w", "Weekly")],
                default="h",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rental_self_service",
            field=models.BooleanField(
                default=False,
                help_text="Allow self-service rental without owner approval",
            ),
        ),
    ]
