# Generated by Django 5.2.7 on 2025-10-07 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_historicalitem_rental_open_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_price__isnull", True),
                    ("rental_price__isnull", True),
                    _connector="OR",
                ),
                name="items_sale_or_rental_price_not_both",
            ),
        ),
    ]
