# Generated by Django 5.2.3 on 2025-06-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_image_fname_alt_item_profile_img_frame_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.IntegerField(
                choices=[(0, "Sell"), (1, "Give Away"), (2, "Borrow"), (3, "Need")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.IntegerField(
                blank=True, choices=[(0, "New"), (1, "Used"), (2, "Old")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemtagrelation",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="tags.itemtag",
            ),
        ),
    ]
