# Generated by Django 5.2.3 on 2025-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="fname_alt",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="profile_img_frame_alt",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
