# Generated by Django 5.2.3 on 2025-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_type_alter_item_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(0, 'For Sale'), (1, 'Give Away'), (2, 'Borrow'), (3, 'Need')], default=0),
        ),
    ]
