# Generated by Django 5.2.3 on 2025-06-25 07:58

import bubble.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_image_fname_alt_alter_item_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["item", "ordering"]},
        ),
        migrations.RemoveField(
            model_name="image",
            name="fname_alt",
        ),
        migrations.AlterField(
            model_name="image",
            name="original",
            field=models.ImageField(
                max_length=255, upload_to=bubble.items.models.upload_to_item_images
            ),
        ),
    ]
