# Generated by Django 5.2.3 on 2025-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_image_options_remove_image_fname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="processing_status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Processing"),
                    (2, "Completed"),
                    (3, "Failed"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
