# Generated by Django 5.2.3 on 2025-06-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_item_item_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemTagRelation",
        ),
    ]
