# Generated by Django 5.2.3 on 2025-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_image_options_remove_image_fname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional fields specific to the item's category",
            ),
        ),
    ]
