# Generated by Django 5.2.3 on 2025-07-02 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_itemcategory_description_and_more"),
        ("items", "0005_item_processing_status_alter_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="categories.itemcategory",
            ),
        ),
    ]
