# Generated by Django 5.2.3 on 2025-07-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_add_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
