# Generated by Django 5.2.3 on 2025-07-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='display_contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='profile_img_frame',
        ),
        migrations.RemoveField(
            model_name='item',
            name='profile_img_frame_alt',
        ),
        migrations.RemoveField(
            model_name='item',
            name='th_payment',
        ),
    ]
