# Generated by Django 5.2.3 on 2025-07-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_remove_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="processing_status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Processing"),
                    (2, "Completed"),
                    (3, "Failed"),
                ],
                default=0,
            ),
        ),
        # migrations.AlterField(
        #     model_name="item",
        #     name="category",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="items",
        #         to="categories.itemcategory",
        #     ),
        # ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
