# Generated by Django 5.2.3 on 2025-07-06 22:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("items", "0007_item_processing_status_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the item",
                unique=False,
            ),
        ),
        # populate existing items with UUIDs
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                setattr(item, "uuid", uuid.uuid4()) or item.save()
                for item in apps.get_model("items", "Item").objects.all()
            ],
            reverse_code=lambda apps, schema_editor: apps.get_model("items", "Item")
            .objects.all()
            .update(uuid=None),
        ),
    ]
