# Generated by Django 5.2.3 on 2025-07-06 22:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_item_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the item",
                unique=True,
            ),
        ),
    ]
