# Generated by Django 5.2.3 on 2025-07-08 05:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0009_alter_item_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.IntegerField(
                choices=[(0, "For Sale"), (1, "Rent")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
            ),
        ),
    ]
