# Generated by Django 5.2.3 on 2025-07-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0015_alter_itemcategory_name"),
        ("items", "0010_alter_item_item_type_alter_item_price"),
    ]

    operations = [
        # Empty migration - fields renamed/added elsewhere or don't exist
    ]
