# Generated by Django 5.2.3 on 2025-07-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0011_remove_item_intern_remove_item_th_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="workflow_id",
            field=models.CharField(
                blank=True,
                help_text="Temporal workflow ID for AI processing",
                max_length=255,
            ),
        ),
    ]
