# Generated by Django 5.2.3 on 2025-07-10 07:59

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_workflow_id'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name='item',
            name='custom_fields',
        ),
        migrations.AddField(
            model_name='item',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector embedding for similarity search', null=True),
        ),
    ]
