# Generated by Django 5.2.3 on 2025-07-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_workflow_id'),
    ]

    operations = [
        # Empty migration - fields were already removed or don't exist
    ]
