# Generated by Django 5.2.3 on 2025-07-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_itemcategory_filters_itemcategory_lower_tag_and_more'),
        ('items', '0013_remove_deleted_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='display_contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='profile_img_frame',
        ),
        migrations.RemoveField(
            model_name='item',
            name='profile_img_frame_alt',
        ),
        migrations.RemoveField(
            model_name='item',
            name='th_payment',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='categories.itemcategory'),
        ),
    ]
