# Generated by Django 5.2.3 on 2025-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_workflow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Used'), (2, 'Old')], default=0, help_text='Condition of the item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(0, 'For Sale'), (1, 'Rent'), (2, 'Give Away')], default=0),
        ),
    ]
