# Generated by Django 5.2.3 on 2025-07-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_status_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(0, 'For Sale'), (1, 'Rent')], default=0),
        ),
    ]
