# Generated by Django 5.2.3 on 2025-07-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0016_alter_item_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="custom_fields",
        ),
    ]
