# Generated by Django 5.2.3 on 2025-07-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0017_remove_item_custom_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="profile_img_frame",
        ),
        migrations.RemoveField(
            model_name="item",
            name="profile_img_frame_alt",
        ),
    ]
