# Generated by Django 5.2.3 on 2025-09-26 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0019_itemcategory_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("books", "Books"),
                    ("clothing", "Clothing"),
                    ("electronics", "Electronics"),
                    ("furniture", "Furniture"),
                    ("garden", "Garden"),
                    ("kitchen", "Kitchen"),
                    ("other", "Other"),
                    ("rooms", "Rooms"),
                    ("sports", "Sports"),
                    ("tools", "Tools"),
                    ("toys", "Toys"),
                    ("vehicles", "Vehicles"),
                ],
                default="",
                help_text="Category of the item",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name="item",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="price",
            new_name="sale_price",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="item",
            name="item_type",
        ),
        migrations.RemoveField(
            model_name="item",
            name="processing_status",
        ),
        migrations.AddField(
            model_name="item",
            name="condition",
            field=models.IntegerField(
                choices=[(0, "New"), (1, "Used"), (2, "Broken")],
                default=1,
                help_text="Condition of the item",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rental_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price per hour for rental items",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Processing"),
                    (2, "Available"),
                    (3, "Reserved"),
                    (4, "Rented"),
                    (5, "Sold"),
                ],
                default=0,
            ),
        ),
        migrations.DeleteModel(
            name="ItemCategory",
        ),
    ]
