# Generated by Django 5.2.3 on 2025-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0020_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("books", "Books"),
                    ("clothing", "Clothing"),
                    ("electronics", "Electronics"),
                    ("furniture", "Furniture"),
                    ("garden", "Garden"),
                    ("kitchen", "Kitchen"),
                    ("other", "Other"),
                    ("rooms", "Rooms"),
                    ("sports", "Sports"),
                    ("tools", "Tools"),
                    ("toys", "Toys"),
                    ("vehicles", "Vehicles"),
                ],
                db_index=True,
                help_text="Category of the item",
                max_length=100,
            ),
        ),
    ]
