# Generated by Django 5.2.3 on 2025-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0021_item_slug_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
