# Generated by Django 5.2.6 on 2025-09-27 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0022_alter_item_name_alter_item_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
