# Generated by Django 5.2.6 on 2025-09-28 11:22

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0024_itemgroupobjectpermission_itemuserobjectpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("books", "Books"),
                            ("clothing", "Clothing"),
                            ("electronics", "Electronics"),
                            ("furniture", "Furniture"),
                            ("garden", "Garden"),
                            ("kitchen", "Kitchen"),
                            ("other", "Other"),
                            ("rooms", "Rooms"),
                            ("sports", "Sports"),
                            ("tools", "Tools"),
                            ("toys", "Toys"),
                            ("vehicles", "Vehicles"),
                        ],
                        db_index=True,
                        help_text="Category of the item",
                        max_length=100,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the item",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "internal",
                    models.BooleanField(
                        default=False, help_text="Internal item, not for public display"
                    ),
                ),
                (
                    "display_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Display your contact information public",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rental_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Price per hour for rental items",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable payment via internal payment system",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "condition",
                    models.IntegerField(
                        choices=[(0, "New"), (1, "Used"), (2, "Broken")],
                        default=1,
                        help_text="Condition of the item",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Processing"),
                            (2, "Available"),
                            (3, "Reserved"),
                            (4, "Rented"),
                            (5, "Sold"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(
                        blank=True,
                        help_text="Temporal workflow ID for AI processing",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item",
                "verbose_name_plural": "historical items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
