# Generated by Django 5.2.7 on 2025-10-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0025_historicalitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"]},
        ),
    ]
