# Generated by Django 5.2.6 on 2025-09-28 11:45

from django.db import migrations


def create_default_groups(apps, schema_editor):
    """Create default groups required by the application."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, created = Group.objects.get_or_create(name="Item Owners")
    if created:
        # assign permission for CRUD on item and image models here
        for perm_codename in [
            "add_item",
            "view_item",
            "add_image",
            "view_image",
        ]:
            permission = Permission.objects.get(
                codename=perm_codename, content_type__app_label="items"
            )
            group.permissions.add(permission)


def reverse_create_default_groups(apps, schema_editor):
    """Remove default groups."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(
        name__in=[
            "Item Owners",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0025_historicalitem"),
    ]

    operations = [
        migrations.RunPython(
            create_default_groups,
            reverse_create_default_groups,
        ),
    ]
