# Generated by Django 5.2.7 on 2025-10-05 12:58

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0027_historicalitem_rental_price_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEmbedding",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding",
                        serialize=False,
                        to="items.item",
                    ),
                ),
                (
                    "vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=384,
                        help_text="Embedding vector for semantic search",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="historicalitem",
            name="workflow_id",
        ),
        migrations.RemoveField(
            model_name="item",
            name="workflow_id",
        ),
    ]
